### ISSUE TITLE
Panic when updating service annotations for EMLB-backed LoadBalancer service

### ISSUE THREAD

**Issue by ctreatma** [kubernetes-sigs/cloud-provider-equinix-metal#477]
During testing we observed the following error, but we're not entirely sure how it happened; one potentially useful piece of information is that the service that caused the error had `port: 8` instead of `port: 80`.

```E1101 16:15:08.976653       1 runtime.go:79] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 180 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d71560?, 0x23be630})
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000f89ce0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x1d71560?, 0x23be630?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/equinix/cloud-provider-equinix-metal/metal/loadbalancers/emlb.(*LB).reconcileService(0xc0004c9e30, {0x23e4fc8, 0xc00022b5e0}, 0xc000333b80, {0xc000324798, 0x1, 0x2c?}, {0xc000194ea0, 0x89})
	/workspace/metal/loadbalancers/emlb/emlb.go:93 +0x368
github.com/equinix/cloud-provider-equinix-metal/metal/loadbalancers/emlb.(*LB).AddService(0xc0009569a0?, {0x23e4fc8?, 0xc00022b5e0?}, {0x0?, 0x4fa00a?}, {0x2?, 0xc0009569a0?}, {0x0?, 0x0?}, {0x0, ...}, ...)
	/workspace/metal/loadbalancers/emlb/emlb.go:62 +0x4d
github.com/equinix/cloud-provider-equinix-metal/metal.(*loadBalancers).addService(0xc000550dc0, {0x23e4fc8, 0xc00022b5e0}, 0xc000333b80, {0xc000324798, 0x1, 0x1}, {0xc000194ea0, 0x89})
	/workspace/metal/loadbalancers.go:533 +0x1d14
github.com/equinix/cloud-provider-equinix-metal/metal.(*loadBalancers).EnsureLoadBalancer(0xc000550dc0, {0x23e4fc8, 0xc00022b5e0}, {0x20b8154, 0xa}, 0xc000542c80?, {0xc000324788, 0x1, 0x1})
	/workspace/metal/loadbalancers.go:192 +0x494
k8s.io/cloud-provider/controllers/service.(*Controller).ensureLoadBalancer(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0}, 0xc000542c80)
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:438 +0x154
k8s.io/cloud-provider/controllers/service.(*Controller).syncLoadBalancerIfNeeded(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0}, 0xc000542c80, {0xc000bba0a0, 0xb})
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:393 +0x752
k8s.io/cloud-provider/controllers/service.(*Controller).processServiceCreateOrUpdate(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0}, 0xc000542c80, {0xc000bba0a0, 0xb})
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:325 +0x13f
k8s.io/cloud-provider/controllers/service.(*Controller).syncService(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0}, {0xc000bba0a0, 0xb})
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:828 +0x27e
k8s.io/cloud-provider/controllers/service.(*Controller).processNextServiceItem(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0})
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:283 +0x119
k8s.io/cloud-provider/controllers/service.(*Controller).serviceWorker(...)
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:250
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:190 +0x22
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:157 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x30?, {0x23c1b60, 0xc000a9e630}, 0x1, 0xc00027e3c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:158 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x410745?, 0x3b9aca00, 0x0, 0x1?, 0xc0004cdf70?)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:135 +0x7f
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x23e4fc8, 0xc00022b5e0}, 0xc000e900b0, 0x3b9aca00?, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:190 +0x93
k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x23e4fc8?, 0xc00022b5e0?}, 0x3ee00000000?, 0x404?)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:101 +0x25
created by k8s.io/cloud-provider/controllers/service.(*Controller).Run in goroutine 362
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:237 +0x43b
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 180 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000f89ce0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x1d71560?, 0x23be630?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/equinix/cloud-provider-equinix-metal/metal/loadbalancers/emlb.(*LB).reconcileService(0xc0004c9e30, {0x23e4fc8, 0xc00022b5e0}, 0xc000333b80, {0xc000324798, 0x1, 0x2c?}, {0xc000194ea0, 0x89})
	/workspace/metal/loadbalancers/emlb/emlb.go:93 +0x368
github.com/equinix/cloud-provider-equinix-metal/metal/loadbalancers/emlb.(*LB).AddService(0xc0009569a0?, {0x23e4fc8?, 0xc00022b5e0?}, {0x0?, 0x4fa00a?}, {0x2?, 0xc0009569a0?}, {0x0?, 0x0?}, {0x0, ...}, ...)
	/workspace/metal/loadbalancers/emlb/emlb.go:62 +0x4d
github.com/equinix/cloud-provider-equinix-metal/metal.(*loadBalancers).addService(0xc000550dc0, {0x23e4fc8, 0xc00022b5e0}, 0xc000333b80, {0xc000324798, 0x1, 0x1}, {0xc000194ea0, 0x89})
	/workspace/metal/loadbalancers.go:533 +0x1d14
github.com/equinix/cloud-provider-equinix-metal/metal.(*loadBalancers).EnsureLoadBalancer(0xc000550dc0, {0x23e4fc8, 0xc00022b5e0}, {0x20b8154, 0xa}, 0xc000542c80?, {0xc000324788, 0x1, 0x1})
	/workspace/metal/loadbalancers.go:192 +0x494
k8s.io/cloud-provider/controllers/service.(*Controller).ensureLoadBalancer(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0}, 0xc000542c80)
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:438 +0x154
k8s.io/cloud-provider/controllers/service.(*Controller).syncLoadBalancerIfNeeded(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0}, 0xc000542c80, {0xc000bba0a0, 0xb})
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:393 +0x752
k8s.io/cloud-provider/controllers/service.(*Controller).processServiceCreateOrUpdate(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0}, 0xc000542c80, {0xc000bba0a0, 0xb})
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:325 +0x13f
k8s.io/cloud-provider/controllers/service.(*Controller).syncService(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0}, {0xc000bba0a0, 0xb})
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:828 +0x27e
k8s.io/cloud-provider/controllers/service.(*Controller).processNextServiceItem(0xc0007eac30, {0x23e4fc8, 0xc00022b5e0})
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:283 +0x119
k8s.io/cloud-provider/controllers/service.(*Controller).serviceWorker(...)
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:250
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:190 +0x22
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:157 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x30?, {0x23c1b60, 0xc000a9e630}, 0x1, 0xc00027e3c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:158 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x410745?, 0x3b9aca00, 0x0, 0x1?, 0xc0004cdf70?)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:135 +0x7f
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x23e4fc8, 0xc00022b5e0}, 0xc000e900b0, 0x3b9aca00?, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:190 +0x93
k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x23e4fc8?, 0xc00022b5e0?}, 0x3ee00000000?, 0x404?)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:101 +0x25
created by k8s.io/cloud-provider/controllers/service.(*Controller).Run in goroutine 362
	/go/pkg/mod/k8s.io/cloud-provider@v0.26.1/controllers/service/controller.go:237 +0x43b
```

The panic comes from this line: https://github.com/kubernetes-sigs/cloud-provider-equinix-metal/blob/main/metal/loadbalancers/emlb/emlb.go#L93

Based on the error message, it sounds like `svc.Annotations` is nil; is that expected in some cases?  If so, we need to code around that.

**Comment by cprivitere** [comment]
I thikn I've reproduced this:
First, deploy a 3 pod nginx deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lbaas-demo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
```
Then create a load balancer for it
```
k expose deployment nginx-deployment --type=LoadBalancer --port=80 --target-port=80
```

**Comment by cprivitere** [comment]
So if I deploy ingress-nginx with helm, there's no crash and everything comes up and works.
When I deploy nginx and expose it with a loadbalancer we get the crash loop and infinite load balancer creation.

**Comment by ctreatma** [comment]
Does the service that is created by `kubectl expose` have annotations?  We might need to update the logic on [these lines](https://github.com/kubernetes-sigs/cloud-provider-equinix-metal/blob/main/metal/loadbalancers/emlb/emlb.go#L93-L94) so that if there isn't already an annotations map, we add one.

**Comment by cprivitere** [comment]
> Does the service that is created by `kubectl expose` have annotations? We might need to update the logic on [these lines](https://github.com/kubernetes-sigs/cloud-provider-equinix-metal/blob/main/metal/loadbalancers/emlb/emlb.go#L93-L94) so that if there isn't already an annotations map, we add one.

Was just coming back here to report that that is exactly the issue. However my proposed fix does not seem to be actually comitting the annotations.

**Comment by ctreatma** [comment]
That...seems like exactly what is supposed to work.  Is it still setting the annotations correctly for the helm service or is it now failing to set them in all cases?

**Comment by cprivitere** [comment]
Tried another iteration:
```
func (l *LB) reconcileService(ctx context.Context, svc *v1.Service, n []*v1.Node, loadBalancerName string) error {
	loadBalancerId := svc.Annotations[LoadBalancerIDAnnotation]

	pools := l.convertToPools(svc, n)

	loadBalancer, err := l.manager.ReconcileLoadBalancer(ctx, loadBalancerId, loadBalancerName, pools)

	if err != nil {
		return err
	}

	svcAfter := svc.DeepCopy()
	svcPatch := client.MergeFrom(svc.DeepCopy())

	annotations := svcAfter.GetAnnotations()
	if annotations == nil {
		annotations = make(map[string]string)
	}

	annotations[LoadBalancerIDAnnotation] = loadBalancer.GetId()
	annotations["equinix.com/loadbalancerMetro"] = l.manager.GetMetro()

	svcAfter.SetAnnotations(annotations)

	return l.client.Patch(ctx, svc, svcPatch)
}
```

```
E0625 16:57:01.273377   20251 controller.go:298] error processing service ingress-nginx/my-ingress-nginx-controller (retrying with exponential backoff): service status returned by EnsureLoadBalancer is nil
I0625 16:57:01.273436   20251 event.go:389] "Event occurred" object="ingress-nginx/my-ingress-nginx-controller" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: service status returned by EnsureLoadBalancer is nil"
I0625 16:57:06.274504   20251 event.go:389] "Event occurred" object="ingress-nginx/my-ingress-nginx-controller" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
E0625 16:57:20.199689   20251 controller.go:298] error processing service ingress-nginx/my-ingress-nginx-controller (retrying with exponential backoff): service status returned by EnsureLoadBalancer is nil
I0625 16:57:20.199911   20251 event.go:389] "Event occurred" object="ingress-nginx/my-ingress-nginx-controller" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: service status returned by EnsureLoadBalancer is nil"
I0625 16:57:30.201124   20251 event.go:389] "Event occurred" object="ingress-nginx/my-ingress-nginx-controller" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
```

**Comment by cprivitere** [comment]
Ok, so THIS is working:

```
func (l *LB) reconcileService(ctx context.Context, svc *v1.Service, n []*v1.Node, loadBalancerName string) error {
	loadBalancerId := svc.Annotations[LoadBalancerIDAnnotation]

	pools := l.convertToPools(svc, n)

	loadBalancer, err := l.manager.ReconcileLoadBalancer(ctx, loadBalancerId, loadBalancerName, pools)

	if err != nil {
		return err
	}

	svcPatch := client.MergeFrom(svc.DeepCopy())

	annotations := svc.GetAnnotations()
	if annotations == nil {
		annotations = make(map[string]string)
	}

	annotations[LoadBalancerIDAnnotation] = loadBalancer.GetId()
	annotations["equinix.com/loadbalancerMetro"] = l.manager.GetMetro()

	svc.SetAnnotations(annotations)

	return l.client.Patch(ctx, svc, svcPatch)
}
```

**Comment by cprivitere** [comment]
Yeah, I deleted it cause it for sure was. 

After a full restart the original code above is just...working now.

**Comment by ctreatma** [comment]
![](https://i.imgflip.com/8v062h.jpg)
